# .github/workflows/trek-watch.yml  (working version)
name: Trek Watch

on:
  schedule:
    - cron: '0 */2 * * *'        # every 2 h  (UTC)
  workflow_dispatch:

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          persist-credentials: true          # needed so we can push

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install Python deps
        run: pip install requests pandas

      - name: Run watcher
        run: python trek_watch.py
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM:  ${{ secrets.MAIL_FROM }}
          MAIL_TO:    ${{ secrets.MAIL_TO }}

      - name: Commit updated state file if it changed
        run: |
          if git diff --quiet trek_seen.json; then
            echo "No new SKUs – nothing to commit."
          else
            git config --global user.email "action@github.com"
            git config --global user.name  "GitHub Actions"
            git add trek_seen.json
            git commit -m "Update seen SKUs $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true
            git push
          fi
