name: Trek Watch

on:
  schedule:
    - cron:  '0 */2 * * *'   # every 2 h (cron uses UTC)
  workflow_dispatch:         # ← allows a manual “Run workflow”

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: pip install requests pandas

      - name: Run watcher
        run: python trek_watch.py
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_FROM:  ${{ secrets.MAIL_FROM }}
          MAIL_TO:    ${{ secrets.MAIL_TO }}

      - name: Commit updated state
        if: |
          success() && (git status --porcelain | grep trek_seen.json)
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name  "GitHub Actions"
          git add trek_seen.json
          git commit -m "Update seen SKUs $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
